const keyData = [
  [
    { dataKey: "`" },
    { dataKey: "1" },
    { dataKey: "2" },
    { dataKey: "3" },
    { dataKey: "4" },
    { dataKey: "5" },
    { dataKey: "6" },
    { dataKey: "7" },
    { dataKey: "8" },
    { dataKey: "9" },
    { dataKey: "0" },
    { dataKey: "-" },
    { dataKey: "=" },
    { dataKey: "Backspace", label: "Del" },
  ],
  [
    { dataKey: "Tab" },
    { dataKey: "q" },
    { dataKey: "w" },
    { dataKey: "e" },
    { dataKey: "r" },
    { dataKey: "t" },
    { dataKey: "y" },
    { dataKey: "u" },
    { dataKey: "i" },
    { dataKey: "o" },
    { dataKey: "p" },
    { dataKey: "[" },
    { dataKey: "]" },
    { dataKey: "\\" },
  ],
  [
    { dataKey: "CapsLock", label: "Caps" },
    { dataKey: "a" },
    { dataKey: "s" },
    { dataKey: "d" },
    { dataKey: "f" },
    { dataKey: "g" },
    { dataKey: "h" },
    { dataKey: "j" },
    { dataKey: "k" },
    { dataKey: "l" },
    { dataKey: ";" },
    { dataKey: "'" },
    { dataKey: "Enter" },
  ],
  [
    { dataKey: "Shift" },
    { dataKey: "z" },
    { dataKey: "x" },
    { dataKey: "c" },
    { dataKey: "v" },
    { dataKey: "b" },
    { dataKey: "n" },
    { dataKey: "m" },
    { dataKey: "," },
    { dataKey: "." },
    { dataKey: "/" },
    { dataKey: "Shift" },
  ],
];

export default keyData;
